algoritmo "semnome"
// Função :
// Autor :
// Data : 04/09/2023
// Seção de Declarações 
var

   par : inteiro

inicio

      escreval()
      
      escreval("----------------- NUMEROS PARES -----------------")
      
      escreval()
      
      par <- 0
      
      escreva ("Os números pares são: ")
      
      Enquanto (par <= 10) Faca
              escreva(par)
              par <- par + 2
      fimenquanto

fimalgoritmo
